default:
    @just --list

# Builds the frontend application
dev:
    @npm run dev

# Install all dependencies in the node_modules
install:
    @npm ci

# Builds the frontend application
build-prod:
    @npm run build-prod

# Builds the spacetimedb backend in development mode
build-dev:
    @npm run build-dev

# Builds an image with the development profile
image-prod:
    @docker build --build-arg PROFILE=prod -t localhost/snake-online-frontend:latest .

# Builds an image with the development profile
image-dev:
    @docker build --build-arg PROFILE=dev -t localhost/snake-online-frontend:latest .

# Run the frontend as a container (requires image to be built previously)
container-run:
    @docker run -d --name snake-online-frontend -p 4200:3000 localhost/snake-online-frontend:latest

# Deploys the application a location
deploy: image-prod
    @echo "TODO implement me!"
