default:
    @just --list

# Builds the spacetimedb backend
build:
    @spacetime build

# Generates the module bindings and puts them into the frontend project
generate:
    @spacetime generate

# Publish the module to local database
publish:
    @spacetime publish --delete-data --yes spacetimedb-demo-snake

# Deploys the application to the maincloud
deploy:
    @echo "TODO implement me!"
