default:
    @just --list

# Builds the spacetimedb backend
build-prod:
    @spacetime build

# Builds the spacetimedb backend in development mode
build-dev:
    @spacetime build --debug

# Generates the module bindings and puts them into the frontend project
generate:
    @spacetime generate

# Publish the module to local database
publish-local:
    @spacetime publish --server local snake-online

# Create an image with the production profile
image:
    @docker build -t localhost/snake-online-backend:latest .

# Run the backend as a container (requires image to be built previously)
container-run:
    @docker run -d --name snake-online-backend -p 3000:3000 snake-online-backend:latest

# Deploys the application to the maincloud
deploy:
    @echo "TODO implement me!"
