default:
    @just --list

# Builds the spacetimedb backend
build:
    @spacetime build

# Builds the spacetimedb backend in development mode
build-dev:
    @spacetime build --debug

# Generates the module bindings and puts them into the frontend project
generate:
    @spacetime generate

# Publish the module to local database
publish-local:
    @spacetime publish --server local snake-online

# Deploys the application to the maincloud
deploy:
    @echo "TODO implement me!"
