// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameState,
  PlayerDto,
  BoardCellContent,
} from "./types";


export default __t.row({
  gameId: __t.u64().name("game_id"),
  name: __t.string(),
  score: __t.u32(),
  get state() {
    return GameState;
  },
  get players() {
    return __t.array(PlayerDto);
  },
  board: __t.array(__t.array(BoardCellContent)),
});
