// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameState,
} from "./types";


export default __t.row({
  gameId: __t.u64().name("game_id"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  owner: __t.identity(),
  name: __t.string(),
  get state() {
    return GameState;
  },
  joinable: __t.bool(),
});
