// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

// The tagged union or sum type for the algebraic type `BoardCellContent`.
export const BoardCellContent = __t.enum('BoardCellContent', {
  None: __t.unit(),
  Snake: __t.unit(),
  Food: __t.unit(),
});
export type BoardCellContent = __Infer<typeof BoardCellContent>;

export const ActiveGameDto = __t.object('ActiveGameDto', {
  gameId: __t.u64(),
  name: __t.string(),
  score: __t.u32(),
  get state() {
    return GameState;
  },
  get players() {
    return __t.array(PlayerDto);
  },
  board: __t.array(__t.array(BoardCellContent)),
});
export type ActiveGameDto = __Infer<typeof ActiveGameDto>;

export const ActivePlayer = __t.object('ActivePlayer', {
  gameId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  activePlayer: __t.identity(),
});
export type ActivePlayer = __Infer<typeof ActivePlayer>;

// The tagged union or sum type for the algebraic type `Direction`.
export const Direction = __t.enum('Direction', {
  Up: __t.unit(),
  Down: __t.unit(),
  Left: __t.unit(),
  Right: __t.unit(),
});
export type Direction = __Infer<typeof Direction>;

export const Food = __t.object('Food', {
  gameId: __t.u64(),
  get position() {
    return Position;
  },
});
export type Food = __Infer<typeof Food>;

export const Game = __t.object('Game', {
  gameId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  owner: __t.identity(),
  name: __t.string(),
  get state() {
    return GameState;
  },
  joinable: __t.bool(),
});
export type Game = __Infer<typeof Game>;

export const GameCleanup = __t.object('GameCleanup', {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.u64(),
});
export type GameCleanup = __Infer<typeof GameCleanup>;

// The tagged union or sum type for the algebraic type `GameState`.
export const GameState = __t.enum('GameState', {
  Idle: __t.unit(),
  Running: __t.unit(),
  GameOver: __t.unit(),
  Win: __t.unit(),
  Closed: __t.unit(),
});
export type GameState = __Infer<typeof GameState>;

export const JoinableGameDto = __t.object('JoinableGameDto', {
  gameId: __t.u64(),
  name: __t.string(),
  ownerName: __t.string(),
  playerCount: __t.u8(),
});
export type JoinableGameDto = __Infer<typeof JoinableGameDto>;

export const NextDirection = __t.object('NextDirection', {
  gameId: __t.u64(),
  get direction() {
    return Direction;
  },
});
export type NextDirection = __Infer<typeof NextDirection>;

export const PlayerDto = __t.object('PlayerDto', {
  identity: __t.identity(),
  name: __t.string(),
  isOwner: __t.bool(),
  isActive: __t.bool(),
});
export type PlayerDto = __Infer<typeof PlayerDto>;

export const Position = __t.object('Position', {
  x: __t.u8(),
  y: __t.u8(),
});
export type Position = __Infer<typeof Position>;

export const Snake = __t.object('Snake', {
  gameId: __t.u64(),
  get body() {
    return __t.array(Position);
  },
});
export type Snake = __Infer<typeof Snake>;

export const User = __t.object('User', {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
  gameId: __t.u64(),
});
export type User = __Infer<typeof User>;
